// Copyright (c) 2025 The Khronos Group Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Generated by cxxbridge. Do not edit manually; re-run `cxxbridge` via the
// instructions in porting-plan.md instead.

#include <array>
#include <cstddef>
#include <cstdint>
#include <new>
#include <string>
#include <type_traits>
#include <utility>
#if __cplusplus >= 201703L
#include <string_view>
#endif

#ifdef __clang__
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#endif // __clang__

namespace rust {
inline namespace cxxbridge1 {
// #include "rust/cxx.h"

struct unsafe_bitcopy_t;

namespace {
template <typename T>
class impl;
} // namespace

#ifndef CXXBRIDGE1_RUST_STRING
#define CXXBRIDGE1_RUST_STRING
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, std::size_t);
  String(const char16_t *);
  String(const char16_t *, std::size_t);
#ifdef __cpp_char8_t
  String(const char8_t *s);
  String(const char8_t *s, std::size_t len);
#endif

  static String lossy(const std::string &) noexcept;
  static String lossy(const char *) noexcept;
  static String lossy(const char *, std::size_t) noexcept;
  static String lossy(const char16_t *) noexcept;
  static String lossy(const char16_t *, std::size_t) noexcept;

  String &operator=(const String &) & noexcept;
  String &operator=(String &&) & noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  const char *c_str() noexcept;

  std::size_t capacity() const noexcept;
  void reserve(size_t new_cap) noexcept;

  using iterator = char *;
  iterator begin() noexcept;
  iterator end() noexcept;

  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const String &) const noexcept;
  bool operator!=(const String &) const noexcept;
  bool operator<(const String &) const noexcept;
  bool operator<=(const String &) const noexcept;
  bool operator>(const String &) const noexcept;
  bool operator>=(const String &) const noexcept;

  void swap(String &) noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  struct lossy_t;
  String(lossy_t, const char *, std::size_t) noexcept;
  String(lossy_t, const char16_t *, std::size_t) noexcept;
  friend void swap(String &lhs, String &rhs) noexcept { lhs.swap(rhs); }

  std::array<std::uintptr_t, 3> repr;
};
#endif // CXXBRIDGE1_RUST_STRING

#ifndef CXXBRIDGE1_RUST_STR
#define CXXBRIDGE1_RUST_STR
class Str final {
public:
  Str() noexcept;
  Str(const String &) noexcept;
  Str(const std::string &);
  Str(const char *);
  Str(const char *, std::size_t);

  Str &operator=(const Str &) & noexcept = default;

  explicit operator std::string() const;
#if __cplusplus >= 201703L
  explicit operator std::string_view() const;
#endif

  const char *data() const noexcept;
  std::size_t size() const noexcept;
  std::size_t length() const noexcept;
  bool empty() const noexcept;

  Str(const Str &) noexcept = default;
  ~Str() noexcept = default;

  using iterator = const char *;
  using const_iterator = const char *;
  const_iterator begin() const noexcept;
  const_iterator end() const noexcept;
  const_iterator cbegin() const noexcept;
  const_iterator cend() const noexcept;

  bool operator==(const Str &) const noexcept;
  bool operator!=(const Str &) const noexcept;
  bool operator<(const Str &) const noexcept;
  bool operator<=(const Str &) const noexcept;
  bool operator>(const Str &) const noexcept;
  bool operator>=(const Str &) const noexcept;

  void swap(Str &) noexcept;

private:
  class uninit;
  Str(uninit) noexcept;
  friend impl<Str>;

  std::array<std::uintptr_t, 2> repr;
};
#endif // CXXBRIDGE1_RUST_STR

namespace detail {
template <typename T, typename = void *>
struct operator_new {
  void *operator()(::std::size_t sz) { return ::operator new(sz); }
};

template <typename T>
struct operator_new<T, decltype(T::operator new(sizeof(T)))> {
  void *operator()(::std::size_t sz) { return T::operator new(sz); }
};
} // namespace detail

template <typename T>
union MaybeUninit {
  T value;
  void *operator new(::std::size_t sz) { return detail::operator_new<T>{}(sz); }
  MaybeUninit() {}
  ~MaybeUninit() {}
};
} // namespace cxxbridge1
} // namespace rust

#if __cplusplus >= 201402L
#define CXX_DEFAULT_VALUE(value) = value
#else
#define CXX_DEFAULT_VALUE(value)
#endif

namespace spvtools {
  namespace ffi {
    struct ParseResult;
  }
}

namespace spvtools {
namespace ffi {
#ifndef CXXBRIDGE1_STRUCT_spvtools$ffi$ParseResult
#define CXXBRIDGE1_STRUCT_spvtools$ffi$ParseResult
struct ParseResult final {
  bool success CXX_DEFAULT_VALUE(false);
  ::std::uint32_t env CXX_DEFAULT_VALUE(0);

  using IsRelocatable = ::std::true_type;
};
#endif // CXXBRIDGE1_STRUCT_spvtools$ffi$ParseResult

extern "C" {
void spvtools$ffi$cxxbridge1$describe_target_env(::std::uint32_t env, ::rust::String *return$) noexcept;

::std::uint32_t spvtools$ffi$cxxbridge1$spirv_version_for_target(::std::uint32_t env) noexcept;

void spvtools$ffi$cxxbridge1$parse_target_env(::rust::Str input, ::spvtools::ffi::ParseResult *return$) noexcept;

void spvtools$ffi$cxxbridge1$parse_vulkan_env(::std::uint32_t vulkan_version, ::std::uint32_t spirv_version, ::spvtools::ffi::ParseResult *return$) noexcept;

bool spvtools$ffi$cxxbridge1$is_vulkan_env(::std::uint32_t env) noexcept;

bool spvtools$ffi$cxxbridge1$is_opencl_env(::std::uint32_t env) noexcept;

bool spvtools$ffi$cxxbridge1$is_opengl_env(::std::uint32_t env) noexcept;

bool spvtools$ffi$cxxbridge1$is_valid_env(::std::uint32_t env) noexcept;

void spvtools$ffi$cxxbridge1$log_namespace(::std::uint32_t env, ::rust::String *return$) noexcept;

void spvtools$ffi$cxxbridge1$list_target_envs(::std::size_t pad, ::std::size_t wrap, ::rust::String *return$) noexcept;
} // extern "C"

::rust::String describe_target_env(::std::uint32_t env) noexcept {
  ::rust::MaybeUninit<::rust::String> return$;
  spvtools$ffi$cxxbridge1$describe_target_env(env, &return$.value);
  return ::std::move(return$.value);
}

::std::uint32_t spirv_version_for_target(::std::uint32_t env) noexcept {
  return spvtools$ffi$cxxbridge1$spirv_version_for_target(env);
}

::spvtools::ffi::ParseResult parse_target_env(::rust::Str input) noexcept {
  ::rust::MaybeUninit<::spvtools::ffi::ParseResult> return$;
  spvtools$ffi$cxxbridge1$parse_target_env(input, &return$.value);
  return ::std::move(return$.value);
}

::spvtools::ffi::ParseResult parse_vulkan_env(::std::uint32_t vulkan_version, ::std::uint32_t spirv_version) noexcept {
  ::rust::MaybeUninit<::spvtools::ffi::ParseResult> return$;
  spvtools$ffi$cxxbridge1$parse_vulkan_env(vulkan_version, spirv_version, &return$.value);
  return ::std::move(return$.value);
}

bool is_vulkan_env(::std::uint32_t env) noexcept {
  return spvtools$ffi$cxxbridge1$is_vulkan_env(env);
}

bool is_opencl_env(::std::uint32_t env) noexcept {
  return spvtools$ffi$cxxbridge1$is_opencl_env(env);
}

bool is_opengl_env(::std::uint32_t env) noexcept {
  return spvtools$ffi$cxxbridge1$is_opengl_env(env);
}

bool is_valid_env(::std::uint32_t env) noexcept {
  return spvtools$ffi$cxxbridge1$is_valid_env(env);
}

::rust::String log_namespace(::std::uint32_t env) noexcept {
  ::rust::MaybeUninit<::rust::String> return$;
  spvtools$ffi$cxxbridge1$log_namespace(env, &return$.value);
  return ::std::move(return$.value);
}

::rust::String list_target_envs(::std::size_t pad, ::std::size_t wrap) noexcept {
  ::rust::MaybeUninit<::rust::String> return$;
  spvtools$ffi$cxxbridge1$list_target_envs(pad, wrap, &return$.value);
  return ::std::move(return$.value);
}
} // namespace ffi
} // namespace spvtools
