#!/usr/bin/env python3
"""Generate the Rust extension allowlist from the SPIR-V tables.

The generator consumes `core_tables_body.inc` produced by the C++ table
generation step (either `build-rust` or `build-cpp`) and emits
`rust/spirv-tools-core/src/target_env/extension_allowlist.rs`.

The output folds in vendor-family defaults:
- NV/NVX/AMDX/QCOM/ARM families are Vulkan-only.
- AMD/GOOGLE/EXT families are allowed for Universal + Vulkan.
- INTEL/ALTERA families are allowed for OpenCL + Universal.
- Explicit Vulkan-only/OpenCL-only overrides mirror the staged rules in
  `TargetEnv::is_extension_allowed`.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFAULT_INPUTS = [
    Path("build-rust/core_tables_body.inc"),
    Path("build-cpp/core_tables_body.inc"),
]
OUTPUT = Path("rust/spirv-tools-core/src/target_env/extension_allowlist.rs")


def read_tables(path: Path) -> str:
    text = path.read_text()
    start = text.find("static const char kStrings[] =")
    if start == -1:
        raise ValueError("could not find kStrings[] in %s" % path)
    lines = []
    for line in text[start:].splitlines():
        lines.append(line)
        if line.strip().endswith(";"):
            break
    return "\n".join(lines)


def extract_extensions(body: str) -> list[str]:
    parts = [m.group(1) for m in re.finditer(r'"(.*?)"', body, re.S)]
    combined = "".join(parts)
    strings = combined.split("\\0")
    extensions: list[str] = []
    for value in strings:
        if value.startswith("SPV_"):
            extensions.append(value)
        else:
            break
    return extensions


def has_prefix(name: str, prefixes: list[str]) -> bool:
    name_lower = name.lower()
    return any(name_lower.startswith(prefix.lower()) for prefix in prefixes)


def compute_allowlist(extensions: list[str]) -> list[tuple[str, bool, bool, bool, bool]]:
    vulkan_only_prefixes = ["SPV_NV_", "SPV_NVX_", "SPV_AMDX_", "SPV_QCOM_", "SPV_ARM_"]
    general_vulkan_universal = ["SPV_AMD_", "SPV_GOOGLE_", "SPV_EXT_"]
    opencl_prefixes = ["SPV_INTEL_", "SPV_ALTERA_"]
    explicit_vulkan_only = {
        "SPV_KHR_vulkan_memory_model",
        "SPV_KHR_workgroup_memory_explicit_layout",
        "SPV_KHR_physical_storage_buffer",
        "SPV_KHR_device_group",
        "SPV_KHR_untyped_pointers",
        "SPV_KHR_maximal_reconvergence",
        "SPV_EXT_descriptor_indexing",
        "SPV_EXT_fragment_shader_interlock",
        "SPV_KHR_fragment_shading_rate",
        "SPV_KHR_fragment_shader_barycentric",
        "SPV_EXT_fragment_invocation_density",
        "SPV_EXT_shader_invocation_reorder",
        "SPV_EXT_mesh_shader",
        "SPV_EXT_shader_atomic_float_add",
        "SPV_EXT_shader_atomic_float_min_max",
        "SPV_KHR_subgroup_uniform_control_flow",
        "SPV_KHR_cooperative_matrix",
        "SPV_EXT_fragment_invocation_density",
        "SPV_NV_shader_invocation_reorder",
        "SPV_NV_cluster_acceleration_structure",
        "SPV_NV_linear_swept_spheres",
        "SPV_KHR_ray_tracing",
        "SPV_KHR_ray_query",
        "SPV_KHR_ray_tracing_position_fetch",
        "SPV_NV_ray_tracing",
        "SPV_NV_ray_tracing_motion_blur",
        "SPV_NV_bindless_texture",
        "SPV_NV_cooperative_matrix",
        "SPV_NV_cooperative_matrix2",
        "SPV_NV_mesh_shader",
        "SPV_QCOM_image_processing",
        "SPV_QCOM_image_processing2",
        "SPV_QCOM_cooperative_matrix_conversion",
        "SPV_QCOM_tile_shading",
        "SPV_KHR_shader_clock",
    }
    opencl_universal = {"SPV_INTEL_function_variants", "SPV_INTEL_fpga_reg"}

    records: list[tuple[str, bool, bool, bool, bool]] = []
    for name in extensions:
        allow_vulkan = allow_opencl = allow_opengl = allow_universal = True
        name_lower = name.lower()
        if "opencl" in name_lower:
            allow_vulkan, allow_opencl, allow_opengl, allow_universal = False, True, False, False
        elif name in explicit_vulkan_only or has_prefix(name, vulkan_only_prefixes):
            allow_vulkan, allow_opencl, allow_opengl, allow_universal = True, False, False, False
        elif name in opencl_universal or has_prefix(name, opencl_prefixes):
            allow_vulkan, allow_opencl, allow_opengl, allow_universal = False, True, False, True
        elif has_prefix(name, general_vulkan_universal):
            allow_vulkan, allow_opencl, allow_opengl, allow_universal = True, False, False, True
        records.append((name, allow_vulkan, allow_opencl, allow_opengl, allow_universal))

    return sorted(records, key=lambda item: item[0].lower())


def render(records: list[tuple[str, bool, bool, bool, bool]]) -> str:
    lines: list[str] = [
        "// @generated by tools/generate_extension_allowlist.py; do not edit",
        "use crate::target_env::TargetEnv;",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct ExtensionAllowlist { pub allow_vulkan: bool, pub allow_opencl: bool, pub allow_opengl: bool, pub allow_universal: bool }",
        "",
        "impl ExtensionAllowlist {",
        "    pub const fn allowed_for(self, env: TargetEnv) -> bool {",
        "        if env.is_vulkan() { return self.allow_vulkan; }",
        "        if env.is_opencl() { return self.allow_opencl; }",
        "        if env.is_opengl() { return self.allow_opengl; }",
        "        if env.is_universal() { return self.allow_universal; }",
        "        false",
        "    }",
        "}",
        "",
        "pub const EXTENSION_ALLOWLIST: &[(&str, ExtensionAllowlist)] = &[",
    ]
    for name, vulkan, opencl, opengl, universal in records:
        lines.append(
            f'    ("{name}", ExtensionAllowlist {{ allow_vulkan: {str(vulkan).lower()}, '
            f"allow_opencl: {str(opencl).lower()}, allow_opengl: {str(opengl).lower()}, "
            f"allow_universal: {str(universal).lower()} }}),"
        )
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--tables",
        type=Path,
        nargs="*",
        help="Paths to core_tables_body.inc (default: build-rust or build-cpp)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help=f"Output path (default: {OUTPUT})",
    )
    args = parser.parse_args()

    candidates = args.tables if args.tables else DEFAULT_INPUTS
    for candidate in candidates:
        if candidate.exists():
            body = read_tables(candidate)
            break
    else:
        raise SystemExit("core_tables_body.inc not found; run CMake first or pass --tables")

    extensions = extract_extensions(body)
    records = compute_allowlist(extensions)
    args.output.write_text(render(records))
    print(f"wrote {args.output} ({len(records)} extensions)")


if __name__ == "__main__":
    main()
