use serde::Deserialize;
use spirv::{Capability as SpirvCapability, Decoration};
use std::env;
use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

#[derive(Deserialize)]
struct CoreGrammar {
    operand_kinds: Vec<OperandKindEntry>,
}

#[derive(Deserialize)]
struct OperandKindEntry {
    kind: String,
    #[serde(default)]
    enumerants: Vec<EnumerantEntry>,
}

#[derive(Deserialize)]
struct EnumerantEntry {
    enumerant: String,
    #[serde(default)]
    parameters: Vec<ParameterEntry>,
    #[serde(default)]
    version: Option<String>,
    #[serde(default)]
    capabilities: Vec<String>,
    #[serde(default)]
    extensions: Vec<String>,
}

#[derive(Deserialize)]
struct ParameterEntry {
    kind: String,
    #[serde(default)]
    quantifier: Option<String>,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let grammar_path = PathBuf::from(&manifest_dir)
        .join("../../external/spirv-headers/include/spirv/unified1/spirv.core.grammar.json");
    let grammar_contents =
        fs::read_to_string(&grammar_path).expect("failed to read spirv.core.grammar.json");
    let grammar: CoreGrammar =
        serde_json::from_str(&grammar_contents).expect("failed to parse core grammar");

    let decoration_entry = grammar
        .operand_kinds
        .iter()
        .find(|kind| kind.kind == "Decoration")
        .expect("Decoration operand kind not found");

    let mut consts = String::new();
    let mut arms = String::new();

    for enumerant in &decoration_entry.enumerants {
        if Decoration::from_str(&enumerant.enumerant).is_err() {
            continue;
        }
        if enumerant.parameters.is_empty() {
            arms.push_str(&format!(
                "        spirv::Decoration::{} => &[],\n",
                enumerant.enumerant
            ));
            continue;
        }
        let const_name = format!("DECORATION_{}_OPERANDS", enumerant.enumerant.to_uppercase());
        consts.push_str(&format!(
            "const {}: &[OperandDescriptor] = &[\n",
            const_name
        ));
        for param in &enumerant.parameters {
            let quantifier = match param.quantifier.as_deref() {
                Some("?") => "OperandQuantifier::ZeroOrOne",
                Some("*") => "OperandQuantifier::ZeroOrMore",
                None => "OperandQuantifier::One",
                Some(other) => panic!(
                    "Unknown quantifier '{}' for decoration {}",
                    other, enumerant.enumerant
                ),
            };
            consts.push_str(&format!(
                "    OperandDescriptor::new(OperandKind::{}, {}),\n",
                param.kind, quantifier
            ));
        }
        consts.push_str(
            "];
",
        );
        arms.push_str(&format!(
            "        spirv::Decoration::{} => {},\n",
            enumerant.enumerant, const_name
        ));
    }

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit\n");
    output.push_str("use rspirv::grammar::{OperandKind, OperandQuantifier};\n");
    output.push_str("use rspirv::spirv;\n");
    output.push_str("use crate::assembly::instruction::OperandDescriptor;\n\n");
    output.push_str(&consts);
    output.push_str("#[allow(unreachable_patterns)]\n");
    output.push_str(
        "pub fn decoration_operand_descriptors(decoration: spirv::Decoration) -> &'static [OperandDescriptor] {\n",
    );
    output.push_str("    match decoration {\n");
    output.push_str(&arms);
    output.push_str("        _ => &[],\n    }\n}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest_path = out_dir.join("decoration_operands.rs");
    fs::write(dest_path, output).expect("failed to write decoration operands");

    // Generate capability metadata (version, required capabilities, required extensions).
    let capability_entry = grammar
        .operand_kinds
        .iter()
        .find(|kind| kind.kind == "Capability")
        .expect("Capability operand kind not found");

    let mut capability_consts = String::new();
    let mut capability_arms = String::new();

    for enumerant in &capability_entry.enumerants {
        if SpirvCapability::from_str(&enumerant.enumerant).is_err() {
            continue;
        }

        let extensions_const = if enumerant.extensions.is_empty() {
            String::from("&[]")
        } else {
            let const_name = format!(
                "CAPABILITY_{}_EXTENSIONS",
                enumerant
                    .enumerant
                    .to_uppercase()
                    .replace(|c: char| !c.is_ascii_alphanumeric(), "_")
            );
            capability_consts.push_str(&format!(
                "const {}: &[&str] = &[{}];\n",
                const_name,
                enumerant
                    .extensions
                    .iter()
                    .map(|ext| format!("\"{}\"", ext))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            const_name
        };

        let dependencies_const = if enumerant.capabilities.is_empty() {
            String::from("&[]")
        } else {
            let const_name = format!(
                "CAPABILITY_{}_REQUIRES",
                enumerant
                    .enumerant
                    .to_uppercase()
                    .replace(|c: char| !c.is_ascii_alphanumeric(), "_")
            );
            capability_consts.push_str(&format!(
                "const {}: &[spirv::Capability] = &[\n",
                const_name
            ));
            for dep in &enumerant.capabilities {
                if SpirvCapability::from_str(dep).is_err() {
                    continue;
                }
                capability_consts.push_str(&format!("    spirv::Capability::{},\n", dep));
            }
            capability_consts.push_str("];\n");
            const_name
        };

        let required_version = enumerant
            .version
            .as_deref()
            .and_then(|version| {
                if version == "None" {
                    None
                } else {
                    Some(version)
                }
            })
            .and_then(|version| {
                let mut parts = version.split('.');
                let major = parts.next()?.parse::<u32>().ok()?;
                let minor = parts.next().unwrap_or("0").parse::<u32>().ok()?;
                Some((major, minor))
            })
            .map(|(major, minor)| format!("Some(SpirvVersion::new({major}, {minor}))"))
            .unwrap_or_else(|| "None".to_string());

        capability_arms.push_str(&format!(
            "        spirv::Capability::{} => CapabilityInfo {{ required_version: {}, required_extensions: {}, required_capabilities: {} }},\n",
            enumerant.enumerant, required_version, extensions_const, dependencies_const
        ));
    }

    let mut capability_output = String::new();
    capability_output.push_str("// @generated by build.rs; do not edit\n");
    capability_output.push_str("use crate::version::SpirvVersion;\n");
    capability_output.push_str("use rspirv::spirv;\n\n");
    capability_output.push_str("#[derive(Clone, Copy)]\n");
    capability_output.push_str("#[allow(dead_code)]\n");
    capability_output.push_str("pub struct CapabilityInfo {\n");
    capability_output.push_str("    pub required_version: Option<SpirvVersion>,\n");
    capability_output.push_str("    pub required_extensions: &'static [&'static str],\n");
    capability_output.push_str("    pub required_capabilities: &'static [spirv::Capability],\n");
    capability_output.push_str("}\n\n");
    capability_output
        .push_str("pub const EMPTY_CAPABILITY_INFO: CapabilityInfo = CapabilityInfo {\n");
    capability_output.push_str("    required_version: None,\n");
    capability_output.push_str("    required_extensions: &[],\n");
    capability_output.push_str("    required_capabilities: &[],\n");
    capability_output.push_str("};\n\n");
    capability_output.push_str(&capability_consts);
    capability_output.push_str("#[allow(unreachable_patterns)]\n");
    capability_output.push_str(
        "pub fn capability_info_from_grammar(capability: spirv::Capability) -> CapabilityInfo {\n",
    );
    capability_output.push_str("    match capability {\n");
    capability_output.push_str(&capability_arms);
    capability_output.push_str("        _ => EMPTY_CAPABILITY_INFO,\n");
    capability_output.push_str("    }\n}\n");

    let capability_dest_path = out_dir.join("capability_info.rs");
    fs::write(capability_dest_path, capability_output).expect("failed to write capability info");
}
