use heck::ToShoutySnakeCase;
use serde::{Deserialize, Deserializer};
use spirv::{Capability as SpirvCapability, Decoration};
use std::env;
use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

#[derive(Deserialize)]
struct CoreGrammar {
    operand_kinds: Vec<OperandKindEntry>,
    instructions: Vec<InstructionEntry>,
}

#[derive(Deserialize)]
struct OperandKindEntry {
    category: String,
    kind: String,
    #[serde(default)]
    enumerants: Vec<EnumerantEntry>,
}

#[derive(Deserialize)]
struct EnumerantEntry {
    enumerant: String,
    #[serde(default)]
    parameters: Vec<ParameterEntry>,
    #[serde(default, deserialize_with = "string_or_int")]
    version: Option<String>,
    #[serde(default)]
    capabilities: Vec<String>,
    #[serde(default)]
    extensions: Vec<String>,
    #[serde(default, deserialize_with = "string_or_int")]
    value: Option<String>,
}

#[derive(Deserialize)]
struct ParameterEntry {
    kind: String,
    #[serde(default)]
    quantifier: Option<String>,
}

#[derive(Deserialize)]
struct InstructionEntry {
    opname: String,
    #[serde(default, deserialize_with = "string_or_int")]
    version: Option<String>,
    #[serde(default)]
    class: Option<String>,
    opcode: u32,
}

fn string_or_int<'de, D>(deserializer: D) -> Result<Option<String>, D::Error>
where
    D: Deserializer<'de>,
{
    let value: Option<serde_json::Value> = Option::deserialize(deserializer)?;
    Ok(value.and_then(|value| match value {
        serde_json::Value::String(s) => Some(s),
        serde_json::Value::Number(n) => Some(n.to_string()),
        _ => None,
    }))
}

fn parse_version(version: Option<&str>) -> Option<(u32, u32)> {
    version
        .and_then(|v| if v == "None" { None } else { Some(v) })
        .and_then(|version| {
            let mut parts = version.split('.');
            let major = parts.next()?.parse::<u32>().ok()?;
            let minor = parts.next().unwrap_or("0").parse::<u32>().ok()?;
            Some((major, minor))
        })
}

fn to_upper_snake(value: &str) -> String {
    let mut ident = value.to_shouty_snake_case();
    if ident
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        ident.insert(0, '_');
    }
    ident
}

fn value_enum_ident(enumerant: &str) -> String {
    if enumerant
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        format!("_{}", enumerant)
    } else {
        enumerant.to_string()
    }
}

fn bit_enum_ident(enumerant: &str) -> String {
    to_upper_snake(enumerant)
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let grammar_path = PathBuf::from(&manifest_dir)
        .join("../../external/spirv-headers/include/spirv/unified1/spirv.core.grammar.json");
    let grammar_contents =
        fs::read_to_string(&grammar_path).expect("failed to read spirv.core.grammar.json");
    let grammar: CoreGrammar =
        serde_json::from_str(&grammar_contents).expect("failed to parse core grammar");

    let decoration_entry = grammar
        .operand_kinds
        .iter()
        .find(|kind| kind.kind == "Decoration")
        .expect("Decoration operand kind not found");

    let mut consts = String::new();
    let mut arms = String::new();

    for enumerant in &decoration_entry.enumerants {
        if Decoration::from_str(&enumerant.enumerant).is_err() {
            continue;
        }
        if enumerant.parameters.is_empty() {
            arms.push_str(&format!(
                "        spirv::Decoration::{} => &[],\n",
                enumerant.enumerant
            ));
            continue;
        }
        let const_name = format!("DECORATION_{}_OPERANDS", enumerant.enumerant.to_uppercase());
        consts.push_str(&format!(
            "const {}: &[OperandDescriptor] = &[\n",
            const_name
        ));
        for param in &enumerant.parameters {
            let quantifier = match param.quantifier.as_deref() {
                Some("?") => "OperandQuantifier::ZeroOrOne",
                Some("*") => "OperandQuantifier::ZeroOrMore",
                None => "OperandQuantifier::One",
                Some(other) => panic!(
                    "Unknown quantifier '{}' for decoration {}",
                    other, enumerant.enumerant
                ),
            };
            consts.push_str(&format!(
                "    OperandDescriptor::new(OperandKind::{}, {}),\n",
                param.kind, quantifier
            ));
        }
        consts.push_str(
            "];
",
        );
        arms.push_str(&format!(
            "        spirv::Decoration::{} => {},\n",
            enumerant.enumerant, const_name
        ));
    }

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit\n");
    output.push_str("use rspirv::grammar::{OperandKind, OperandQuantifier};\n");
    output.push_str("use rspirv::spirv;\n");
    output.push_str("use crate::assembly::instruction::OperandDescriptor;\n\n");
    output.push_str(&consts);
    output.push_str("#[allow(unreachable_patterns)]\n");
    output.push_str(
        "pub fn decoration_operand_descriptors(decoration: spirv::Decoration) -> &'static [OperandDescriptor] {\n",
    );
    output.push_str("    match decoration {\n");
    output.push_str(&arms);
    output.push_str("        _ => &[],\n    }\n}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest_path = out_dir.join("decoration_operands.rs");
    fs::write(dest_path, output).expect("failed to write decoration operands");

    // Generate capability metadata (version, required capabilities, required extensions).
    let capability_entry = grammar
        .operand_kinds
        .iter()
        .find(|kind| kind.kind == "Capability")
        .expect("Capability operand kind not found");

    let mut capability_consts = String::new();
    let mut capability_arms = String::new();

    for enumerant in &capability_entry.enumerants {
        if SpirvCapability::from_str(&enumerant.enumerant).is_err() {
            continue;
        }

        let extensions_const = if enumerant.extensions.is_empty() {
            String::from("&[]")
        } else {
            let const_name = format!(
                "CAPABILITY_{}_EXTENSIONS",
                enumerant
                    .enumerant
                    .to_uppercase()
                    .replace(|c: char| !c.is_ascii_alphanumeric(), "_")
            );
            capability_consts.push_str(&format!(
                "const {}: &[&str] = &[{}];\n",
                const_name,
                enumerant
                    .extensions
                    .iter()
                    .map(|ext| format!("\"{}\"", ext))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            const_name
        };

        let dependencies_const = if enumerant.capabilities.is_empty() {
            String::from("&[]")
        } else {
            let const_name = format!(
                "CAPABILITY_{}_REQUIRES",
                enumerant
                    .enumerant
                    .to_uppercase()
                    .replace(|c: char| !c.is_ascii_alphanumeric(), "_")
            );
            capability_consts.push_str(&format!(
                "const {}: &[spirv::Capability] = &[\n",
                const_name
            ));
            for dep in &enumerant.capabilities {
                if SpirvCapability::from_str(dep).is_err() {
                    continue;
                }
                capability_consts.push_str(&format!("    spirv::Capability::{},\n", dep));
            }
            capability_consts.push_str("];\n");
            const_name
        };

        let required_version = parse_version(enumerant.version.as_deref())
            .map(|(major, minor)| format!("Some(SpirvVersion::new({major}, {minor}))"))
            .unwrap_or_else(|| "None".to_string());

        capability_arms.push_str(&format!(
            "        spirv::Capability::{} => CapabilityInfo {{ required_version: {}, required_extensions: {}, required_capabilities: {} }},\n",
            enumerant.enumerant, required_version, extensions_const, dependencies_const
        ));
    }

    let mut capability_output = String::new();
    capability_output.push_str("// @generated by build.rs; do not edit\n");
    capability_output.push_str("use crate::version::SpirvVersion;\n");
    capability_output.push_str("use rspirv::spirv;\n\n");
    capability_output.push_str("#[derive(Clone, Copy)]\n");
    capability_output.push_str("#[allow(dead_code)]\n");
    capability_output.push_str("pub struct CapabilityInfo {\n");
    capability_output.push_str("    pub required_version: Option<SpirvVersion>,\n");
    capability_output.push_str("    pub required_extensions: &'static [&'static str],\n");
    capability_output.push_str("    pub required_capabilities: &'static [spirv::Capability],\n");
    capability_output.push_str("}\n\n");
    capability_output
        .push_str("pub const EMPTY_CAPABILITY_INFO: CapabilityInfo = CapabilityInfo {\n");
    capability_output.push_str("    required_version: None,\n");
    capability_output.push_str("    required_extensions: &[],\n");
    capability_output.push_str("    required_capabilities: &[],\n");
    capability_output.push_str("};\n\n");
    capability_output.push_str(&capability_consts);
    capability_output.push_str("#[allow(unreachable_patterns)]\n");
    capability_output.push_str(
        "pub fn capability_info_from_grammar(capability: spirv::Capability) -> CapabilityInfo {\n",
    );
    capability_output.push_str("    match capability {\n");
    capability_output.push_str(&capability_arms);
    capability_output.push_str("        _ => EMPTY_CAPABILITY_INFO,\n");
    capability_output.push_str("    }\n}\n");

    let capability_dest_path = out_dir.join("capability_info.rs");
    fs::write(capability_dest_path, capability_output).expect("failed to write capability info");

    // Generate instruction→minimum-SPIR-V-version mapping from the grammar.
    let mut instruction_version_arms = String::new();
    for inst in &grammar.instructions {
        if let Some((major, minor)) = parse_version(inst.version.as_deref()) {
            // Skip baseline 1.0 entries to keep the table compact.
            if major == 1 && minor == 0 {
                continue;
            }
            let variant = inst
                .opname
                .strip_prefix("Op")
                .unwrap_or(inst.opname.as_str());
            instruction_version_arms.push_str(&format!(
                "        spirv::Op::{} => Some(SpirvVersion::new({major}, {minor})),\n",
                variant
            ));
        }
    }

    let mut instruction_output = String::new();
    instruction_output.push_str("// @generated by build.rs; do not edit\n");
    instruction_output.push_str("use crate::version::SpirvVersion;\n");
    instruction_output.push_str("use rspirv::spirv;\n\n");
    instruction_output.push_str(
        "pub fn grammar_required_spirv_version_for_opcode(opcode: spirv::Op) -> Option<SpirvVersion> {\n",
    );
    instruction_output.push_str("    match opcode {\n");
    instruction_output.push_str(&instruction_version_arms);
    instruction_output.push_str("        _ => None,\n");
    instruction_output.push_str("    }\n}\n");

    let instruction_dest_path = out_dir.join("instruction_versions.rs");
    fs::write(instruction_dest_path, instruction_output)
        .expect("failed to write instruction version table");

    // Generate operand→minimum-SPIR-V-version mapping for both value and bit enums.
    let mut operand_helpers = String::new();
    let mut operand_match_arms = String::new();
    let mut has_bit_enum = false;

    for kind in &grammar.operand_kinds {
        let enumerant_versions: Vec<_> = kind
            .enumerants
            .iter()
            .filter_map(|enumerant| {
                parse_version(enumerant.version.as_deref()).map(|(major, minor)| {
                    (
                        enumerant.enumerant.as_str(),
                        (major, minor),
                        enumerant.value.as_deref(),
                    )
                })
            })
            .filter(|(_, (major, minor), _)| !(*major == 1 && *minor == 0))
            .collect();

        if enumerant_versions.is_empty() {
            continue;
        }

        let fn_name = format!("operand_version_for_{}", kind.kind.to_lowercase());

        match kind.category.as_str() {
            "ValueEnum" => {
                operand_helpers.push_str(&format!(
                    "#[allow(unreachable_patterns)]\nfn {fn_name}(value: spirv::{kind}) -> Option<SpirvVersion> {{\n",
                    kind = kind.kind
                ));
                operand_helpers.push_str("    match value {\n");
                for (enumerant, (major, minor), _) in &enumerant_versions {
                    let enumerant_ident = value_enum_ident(enumerant);
                    operand_helpers.push_str(&format!(
                        "        spirv::{kind}::{enumerant} => Some(SpirvVersion::new({major}, {minor})),\n",
                        kind = kind.kind,
                        enumerant = enumerant_ident
                    ));
                }
                operand_helpers.push_str("        _ => None,\n    }\n}\n\n");
                operand_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}(value) => {fn_name}(*value),\n",
                    kind = kind.kind
                ));
            }
            "BitEnum" => {
                has_bit_enum = true;
                operand_helpers.push_str(&format!(
                    "#[allow(unreachable_patterns)]\nfn {fn_name}(value: spirv::{kind}) -> Option<SpirvVersion> {{\n",
                    kind = kind.kind
                ));
                operand_helpers.push_str("    let mut required: Option<SpirvVersion> = None;\n");
                for (enumerant, (major, minor), _) in &enumerant_versions {
                    let enumerant_ident = bit_enum_ident(enumerant);
                    operand_helpers.push_str(&format!(
                        "    if value.contains(spirv::{kind}::{enumerant}) {{ merge_version(&mut required, SpirvVersion::new({major}, {minor})); }}\n",
                        kind = kind.kind,
                        enumerant = enumerant_ident
                    ));
                }
                operand_helpers.push_str("    required\n}\n\n");
                operand_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}(value) => {fn_name}(*value),\n",
                    kind = kind.kind
                ));
            }
            _ => {}
        }
    }

    let mut operand_output = String::new();
    operand_output.push_str("// @generated by build.rs; do not edit\n");
    operand_output.push_str("use crate::version::SpirvVersion;\n");
    operand_output.push_str("use rspirv::{dr::Operand, spirv};\n\n");
    if has_bit_enum {
        operand_output.push_str(
            "fn merge_version(target: &mut Option<SpirvVersion>, candidate: SpirvVersion) {\n",
        );
        operand_output
            .push_str("    if target.map(|current| current < candidate).unwrap_or(true) {\n");
        operand_output.push_str("        *target = Some(candidate);\n    }\n}\n\n");
    }
    operand_output.push_str(&operand_helpers);
    operand_output.push_str(
        "pub fn grammar_required_spirv_version_for_operand(operand: &Operand) -> Option<SpirvVersion> {\n",
    );
    operand_output.push_str("    match operand {\n");
    operand_output.push_str(&operand_match_arms);
    operand_output.push_str("        _ => None,\n");
    operand_output.push_str("    }\n}\n");

    let operand_dest_path = out_dir.join("operand_versions.rs");
    fs::write(operand_dest_path, operand_output).expect("failed to write operand version table");

    // Generate operand capability/extension requirements from the grammar.
    let mut requirement_helpers = String::new();
    let mut cap_match_arms = String::new();
    let mut ext_match_arms = String::new();

    for kind in &grammar.operand_kinds {
        let has_capabilities = kind
            .enumerants
            .iter()
            .any(|enumerant| !enumerant.capabilities.is_empty());
        let has_extensions = kind
            .enumerants
            .iter()
            .any(|enumerant| !enumerant.extensions.is_empty());
        if !has_capabilities && !has_extensions {
            continue;
        }

        let fn_caps = format!("operand_capabilities_for_{}", kind.kind.to_lowercase());
        let fn_exts = format!("operand_extensions_for_{}", kind.kind.to_lowercase());

        match kind.category.as_str() {
            "ValueEnum" => {
                if has_capabilities {
                    let mut cap_arms = String::new();
                    for enumerant in &kind.enumerants {
                        if let Some(raw) = enumerant.value.as_deref() {
                            let capabilities = enumerant
                                .capabilities
                                .iter()
                                .filter_map(|cap| SpirvCapability::from_str(cap).ok())
                                .map(|cap| format!("spirv::Capability::{cap:?}"))
                                .collect::<Vec<_>>();
                            if !capabilities.is_empty() {
                                cap_arms.push_str(&format!(
                                    "        {raw} => caps.extend([{capabilities}]),\n",
                                    raw = raw,
                                    capabilities = capabilities.join(", ")
                                ));
                            }
                        }
                    }
                    if cap_arms.is_empty() {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_caps}(_value: spirv::{kind}) -> Vec<spirv::Capability> {{ Vec::new() }}\n\n",
                            kind = kind.kind
                        ));
                    } else {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_caps}(value: spirv::{kind}) -> Vec<spirv::Capability> {{\n    let mut caps = Vec::new();\n    match value as u32 {{\n{cap_arms}        _ => {{}}\n    }}\n    caps\n}}\n\n",
                            fn_caps = fn_caps,
                            kind = kind.kind,
                            cap_arms = cap_arms
                        ));
                    }
                }
                if has_extensions {
                    let mut ext_arms = String::new();
                    for enumerant in &kind.enumerants {
                        if let Some(raw) = enumerant.value.as_deref() {
                            let extensions = enumerant
                                .extensions
                                .iter()
                                .map(|ext| format!("\"{ext}\""))
                                .collect::<Vec<_>>();
                            if !extensions.is_empty() {
                                ext_arms.push_str(&format!(
                                    "        {raw} => exts.extend([{extensions}]),\n",
                                    raw = raw,
                                    extensions = extensions.join(", ")
                                ));
                            }
                        }
                    }
                    if ext_arms.is_empty() {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_exts}(_value: spirv::{kind}) -> Vec<&'static str> {{ Vec::new() }}\n\n",
                            kind = kind.kind
                        ));
                    } else {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_exts}(value: spirv::{kind}) -> Vec<&'static str> {{\n    let mut exts = Vec::new();\n    match value as u32 {{\n{ext_arms}        _ => {{}}\n    }}\n    exts\n}}\n\n",
                            fn_exts = fn_exts,
                            kind = kind.kind,
                            ext_arms = ext_arms
                        ));
                    }
                }
                let cap_binding = if has_capabilities { "value" } else { "_" };
                let cap_expr = if has_capabilities {
                    format!("{fn_caps}(*value)")
                } else {
                    "Vec::new()".to_string()
                };
                cap_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}({cap_binding}) => {caps},\n",
                    kind = kind.kind,
                    cap_binding = cap_binding,
                    caps = cap_expr
                ));

                let ext_binding = if has_extensions { "value" } else { "_" };
                let ext_expr = if has_extensions {
                    format!("{fn_exts}(*value)")
                } else {
                    "Vec::new()".to_string()
                };
                ext_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}({ext_binding}) => {exts},\n",
                    kind = kind.kind,
                    ext_binding = ext_binding,
                    exts = ext_expr
                ));
            }
            "BitEnum" => {
                if has_capabilities {
                    let mut cap_lines = String::new();
                    for enumerant in &kind.enumerants {
                        if let Some(raw) = enumerant.value.as_deref() {
                            // Skip zero-valued flag entries; they do not gate any capabilities.
                            if raw == "0" {
                                continue;
                            }
                            let capabilities = enumerant
                                .capabilities
                                .iter()
                                .filter_map(|cap| SpirvCapability::from_str(cap).ok())
                                .map(|cap| format!("spirv::Capability::{cap:?}"))
                                .collect::<Vec<_>>();
                            if !capabilities.is_empty() {
                                cap_lines.push_str(&format!(
                                    "    if (value.bits() & {raw}) != 0 {{ caps.extend([{capabilities}]); }}\n",
                                    raw = raw,
                                    capabilities = capabilities.join(", ")
                                ));
                            }
                        }
                    }
                    if cap_lines.is_empty() {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_caps}(_value: spirv::{kind}) -> Vec<spirv::Capability> {{ Vec::new() }}\n\n",
                            kind = kind.kind
                        ));
                    } else {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_caps}(value: spirv::{kind}) -> Vec<spirv::Capability> {{\n    let mut caps = Vec::new();\n{cap_lines}    caps\n}}\n\n",
                            fn_caps = fn_caps,
                            kind = kind.kind,
                            cap_lines = cap_lines
                        ));
                    }
                }
                if has_extensions {
                    let mut ext_lines = String::new();
                    for enumerant in &kind.enumerants {
                        if let Some(raw) = enumerant.value.as_deref() {
                            // Skip zero-valued flag entries; they do not gate extensions.
                            if raw == "0" {
                                continue;
                            }
                            let extensions = enumerant
                                .extensions
                                .iter()
                                .map(|ext| format!("\"{ext}\""))
                                .collect::<Vec<_>>();
                            if !extensions.is_empty() {
                                ext_lines.push_str(&format!(
                                    "    if (value.bits() & {raw}) != 0 {{ exts.extend([{extensions}]); }}\n",
                                    raw = raw,
                                    extensions = extensions.join(", ")
                                ));
                            }
                        }
                    }
                    if ext_lines.is_empty() {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_exts}(_value: spirv::{kind}) -> Vec<&'static str> {{ Vec::new() }}\n\n",
                            kind = kind.kind
                        ));
                    } else {
                        requirement_helpers.push_str(&format!(
                            "fn {fn_exts}(value: spirv::{kind}) -> Vec<&'static str> {{\n    let mut exts = Vec::new();\n{ext_lines}    exts\n}}\n\n",
                            fn_exts = fn_exts,
                            kind = kind.kind,
                            ext_lines = ext_lines
                        ));
                    }
                }
                let cap_binding = if has_capabilities { "value" } else { "_" };
                let cap_expr = if has_capabilities {
                    format!("{fn_caps}(*value)")
                } else {
                    "Vec::new()".to_string()
                };
                cap_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}({cap_binding}) => {caps},\n",
                    kind = kind.kind,
                    cap_binding = cap_binding,
                    caps = cap_expr
                ));

                let ext_binding = if has_extensions { "value" } else { "_" };
                let ext_expr = if has_extensions {
                    format!("{fn_exts}(*value)")
                } else {
                    "Vec::new()".to_string()
                };
                ext_match_arms.push_str(&format!(
                    "        rspirv::dr::Operand::{kind}({ext_binding}) => {exts},\n",
                    kind = kind.kind,
                    ext_binding = ext_binding,
                    exts = ext_expr
                ));
            }
            _ => {}
        }
    }

    let mut requirement_output = String::new();
    requirement_output.push_str("// @generated by build.rs; do not edit\n");
    requirement_output.push_str("use rspirv::{dr::Operand, spirv};\n\n");
    requirement_output.push_str(&requirement_helpers);
    requirement_output.push_str(
        "pub fn grammar_required_capabilities_for_operand(operand: &Operand) -> Vec<spirv::Capability> {\n",
    );
    requirement_output.push_str("    match operand {\n");
    requirement_output.push_str(&cap_match_arms);
    requirement_output.push_str("        _ => Vec::new(),\n    }\n}\n\n");
    requirement_output.push_str(
        "pub fn grammar_required_extensions_for_operand(operand: &Operand) -> Vec<&'static str> {\n",
    );
    requirement_output.push_str("    match operand {\n");
    requirement_output.push_str(&ext_match_arms);
    requirement_output.push_str("        _ => Vec::new(),\n    }\n}\n");

    let requirement_dest_path = out_dir.join("operand_requirements.rs");
    fs::write(requirement_dest_path, requirement_output)
        .expect("failed to write operand requirement table");

    // Generate instruction→class mapping for layout enforcement so new grammar entries are covered.
    let mut class_match_arms = String::new();
    for inst in &grammar.instructions {
        let class = match inst.class.as_deref() {
            Some("Annotation") => "Annotation",
            Some("Constant-Creation") => "ConstantCreation",
            Some("Debug") => "Debug",
            Some("Extension") => "Extension",
            Some("Mode-Setting") => "ModeSetting",
            Some("Type-Declaration") => "TypeDeclaration",
            _ => continue,
        };
        if spirv::Op::from_u32(inst.opcode).is_none() {
            continue;
        }
        let mut variant = inst
            .opname
            .strip_prefix("Op")
            .unwrap_or(inst.opname.as_str())
            .to_string();
        if variant.contains("ALTERA") {
            variant = variant.replace("ALTERA", "INTEL");
        }
        class_match_arms.push_str(&format!(
            "        spirv::Op::{variant} => Some(InstructionClass::{class}),\n"
        ));
    }

    let mut class_output = String::new();
    class_output.push_str("// @generated by build.rs; do not edit\n");
    class_output.push_str("use rspirv::spirv;\n\n");
    class_output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    class_output.push_str("pub enum InstructionClass {\n");
    class_output.push_str("    Annotation,\n");
    class_output.push_str("    ConstantCreation,\n");
    class_output.push_str("    Debug,\n");
    class_output.push_str("    Extension,\n");
    class_output.push_str("    ModeSetting,\n");
    class_output.push_str("    TypeDeclaration,\n");
    class_output.push_str("}\n\n");
    class_output
        .push_str("pub fn instruction_class(opcode: spirv::Op) -> Option<InstructionClass> {\n");
    class_output.push_str("    match opcode {\n");
    class_output.push_str(&class_match_arms);
    class_output.push_str("        _ => None,\n    }\n}\n");

    let class_dest_path = out_dir.join("instruction_classes.rs");
    fs::write(class_dest_path, class_output).expect("failed to write instruction class table");

    // Generate mode-setting ordering mapping so layout checks track grammar additions.
    let mut mode_setting_match_arms = String::new();
    let mut mode_stage_match_arms = String::new();
    let mut capability_op_match_arms = String::new();
    let mut extension_op_match_arms = String::new();
    for inst in &grammar.instructions {
        let (kind, stage) = match inst.opname.as_str() {
            "OpCapability" => ("Capability", Some("Capabilities")),
            "OpConditionalCapabilityINTEL" => ("ConditionalCapability", Some("Capabilities")),
            "OpExtension" => ("Extension", Some("Extensions")),
            "OpConditionalExtensionINTEL" => ("ConditionalExtension", Some("Extensions")),
            "OpExtInstImport" => ("ExtInstImport", Some("ExtInstImport")),
            "OpMemoryModel" => ("MemoryModel", Some("MemoryModel")),
            "OpEntryPoint" => ("EntryPoint", Some("EntryPoint")),
            "OpConditionalEntryPointINTEL" => ("ConditionalEntryPoint", Some("EntryPoint")),
            "OpExecutionMode" => ("ExecutionMode", Some("ExecutionMode")),
            "OpExecutionModeId" => ("ExecutionModeId", Some("ExecutionMode")),
            _ => ("Other", None),
        };
        if spirv::Op::from_u32(inst.opcode).is_none() {
            continue;
        }
        if kind == "Other" && stage.is_none() {
            continue;
        }
        let mut variant = inst
            .opname
            .strip_prefix("Op")
            .unwrap_or(inst.opname.as_str())
            .to_string();
        if variant.contains("ALTERA") {
            variant = variant.replace("ALTERA", "INTEL");
        }
        mode_setting_match_arms.push_str(&format!(
            "        spirv::Op::{variant} => Some(ModeSettingKind::{kind}),\n"
        ));
        if let Some(stage) = stage {
            mode_stage_match_arms.push_str(&format!(
                "        spirv::Op::{variant} => Some(ModeStage::{stage}),\n"
            ));
        }
        match kind {
            "Capability" | "ConditionalCapability" => capability_op_match_arms
                .push_str(&format!("        spirv::Op::{variant} => true,\n")),
            "Extension" | "ConditionalExtension" => extension_op_match_arms
                .push_str(&format!("        spirv::Op::{variant} => true,\n")),
            _ => {}
        }
    }

    let mut mode_setting_output = String::new();
    mode_setting_output.push_str("// @generated by build.rs; do not edit\n");
    mode_setting_output.push_str("use rspirv::spirv;\n\n");
    mode_setting_output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
    mode_setting_output.push_str("#[allow(dead_code)]\n");
    mode_setting_output.push_str("pub enum ModeSettingKind {\n");
    mode_setting_output.push_str("    Capability,\n");
    mode_setting_output.push_str("    ConditionalCapability,\n");
    mode_setting_output.push_str("    Extension,\n");
    mode_setting_output.push_str("    ConditionalExtension,\n");
    mode_setting_output.push_str("    ExtInstImport,\n");
    mode_setting_output.push_str("    MemoryModel,\n");
    mode_setting_output.push_str("    EntryPoint,\n");
    mode_setting_output.push_str("    ConditionalEntryPoint,\n");
    mode_setting_output.push_str("    ExecutionMode,\n");
    mode_setting_output.push_str("    ExecutionModeId,\n");
    mode_setting_output.push_str("    Other,\n");
    mode_setting_output.push_str("}\n\n");
    mode_setting_output
        .push_str("pub fn mode_setting_kind(opcode: spirv::Op) -> Option<ModeSettingKind> {\n");
    mode_setting_output.push_str("    match opcode {\n");
    mode_setting_output.push_str(&mode_setting_match_arms);
    mode_setting_output.push_str("        _ => None,\n    }\n}\n\n");

    mode_setting_output.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]\n");
    mode_setting_output.push_str("#[allow(dead_code)]\n");
    mode_setting_output.push_str("pub enum ModeStage {\n");
    mode_setting_output.push_str("    Capabilities,\n");
    mode_setting_output.push_str("    Extensions,\n");
    mode_setting_output.push_str("    ExtInstImport,\n");
    mode_setting_output.push_str("    MemoryModel,\n");
    mode_setting_output.push_str("    EntryPoint,\n");
    mode_setting_output.push_str("    ExecutionMode,\n");
    mode_setting_output.push_str("}\n\n");
    mode_setting_output.push_str("#[allow(dead_code)]\n");
    mode_setting_output.push_str("pub fn mode_stage(opcode: spirv::Op) -> Option<ModeStage> {\n");
    mode_setting_output.push_str("    match opcode {\n");
    mode_setting_output.push_str(&mode_stage_match_arms);
    mode_setting_output.push_str("        _ => None,\n    }\n}\n");

    mode_setting_output.push_str("\n#[allow(dead_code)]\n");
    mode_setting_output.push_str("pub fn is_capability_opcode(opcode: spirv::Op) -> bool {\n");
    mode_setting_output.push_str("    match opcode {\n");
    mode_setting_output.push_str(&capability_op_match_arms);
    mode_setting_output.push_str("        _ => false,\n    }\n}\n");

    mode_setting_output.push_str("\n#[allow(dead_code)]\n");
    mode_setting_output.push_str("pub fn is_extension_opcode(opcode: spirv::Op) -> bool {\n");
    mode_setting_output.push_str("    match opcode {\n");
    mode_setting_output.push_str(&extension_op_match_arms);
    mode_setting_output.push_str("        _ => false,\n    }\n}\n");

    let mode_setting_dest_path = out_dir.join("instruction_layout.rs");
    fs::write(mode_setting_dest_path, mode_setting_output)
        .expect("failed to write instruction layout table");
}
