use serde::Deserialize;
use spirv::Decoration;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::str::FromStr;

#[derive(Deserialize)]
struct CoreGrammar {
    operand_kinds: Vec<OperandKindEntry>,
}

#[derive(Deserialize)]
struct OperandKindEntry {
    kind: String,
    #[serde(default)]
    enumerants: Vec<EnumerantEntry>,
}

#[derive(Deserialize)]
struct EnumerantEntry {
    enumerant: String,
    #[serde(default)]
    parameters: Vec<ParameterEntry>,
}

#[derive(Deserialize)]
struct ParameterEntry {
    kind: String,
    #[serde(default)]
    quantifier: Option<String>,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let grammar_path = PathBuf::from(&manifest_dir)
        .join("../../external/spirv-headers/include/spirv/unified1/spirv.core.grammar.json");
    let grammar_contents =
        fs::read_to_string(&grammar_path).expect("failed to read spirv.core.grammar.json");
    let grammar: CoreGrammar =
        serde_json::from_str(&grammar_contents).expect("failed to parse core grammar");

    let decoration_entry = grammar
        .operand_kinds
        .iter()
        .find(|kind| kind.kind == "Decoration")
        .expect("Decoration operand kind not found");

    let mut consts = String::new();
    let mut arms = String::new();

    for enumerant in &decoration_entry.enumerants {
        if Decoration::from_str(&enumerant.enumerant).is_err() {
            continue;
        }
        if enumerant.parameters.is_empty() {
            arms.push_str(&format!(
                "        spirv::Decoration::{} => &[],\n",
                enumerant.enumerant
            ));
            continue;
        }
        let const_name = format!("DECORATION_{}_OPERANDS", enumerant.enumerant.to_uppercase());
        consts.push_str(&format!(
            "const {}: &[OperandDescriptor] = &[\n",
            const_name
        ));
        for param in &enumerant.parameters {
            let quantifier = match param.quantifier.as_deref() {
                Some("?") => "OperandQuantifier::ZeroOrOne",
                Some("*") => "OperandQuantifier::ZeroOrMore",
                None => "OperandQuantifier::One",
                Some(other) => panic!(
                    "Unknown quantifier '{}' for decoration {}",
                    other, enumerant.enumerant
                ),
            };
            consts.push_str(&format!(
                "    OperandDescriptor::new(OperandKind::{}, {}),\n",
                param.kind, quantifier
            ));
        }
        consts.push_str(
            "];
",
        );
        arms.push_str(&format!(
            "        spirv::Decoration::{} => {},\n",
            enumerant.enumerant, const_name
        ));
    }

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit\n");
    output.push_str("use rspirv::grammar::{OperandKind, OperandQuantifier};\n");
    output.push_str("use rspirv::spirv;\n");
    output.push_str("use crate::assembly::instruction::OperandDescriptor;\n\n");
    output.push_str(&consts);
    output.push_str("#[allow(unreachable_patterns)]\n");
    output.push_str(
        "pub fn decoration_operand_descriptors(decoration: spirv::Decoration) -> &'static [OperandDescriptor] {\n",
    );
    output.push_str("    match decoration {\n");
    output.push_str(&arms);
    output.push_str("        _ => &[],\n    }\n}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let dest_path = out_dir.join("decoration_operands.rs");
    fs::write(dest_path, output).expect("failed to write decoration operands");
}
