[workspace]
members = [
    "spirv-tools",
    "spirv-tools-core",
    "spirv-tools-cli",
    "spirv-tools-ffi",
    "spirv-tools-opt",
]
resolver = "2"

[patch.crates-io]
rspirv = { git = "https://github.com/gfx-rs/rspirv", branch = "sdk-update" }
spirv = { git = "https://github.com/gfx-rs/rspirv", branch = "sdk-update", package = "spirv" }
